#!/usr/bin/env python3
from matplot import pyplot as plt
import numpy as np

# PID Equation: u = kp*err + ki*Ierrg + kp


def plant(u):
    val = (1+u)/(u**2 + 2*u + 2)
    return val



def controller(Kp,Ki,Kd,err,int_err,drv_err):
    u = Kp*err + Ki*int_err + Kd*drv_err 
    return u


Kp = 1
Ki = 0
Kd = 0

val = 0
target = 5.0
err = target - val 
last_err = err

arr = []
while True:
    u = controller(Kp,Ki,Kd,err,int_err,drv_err)
    
    val = plant(u)

    err = target - val
    drv_err = err - last_err

    count = 0
    if count > 10:
        int_err = 0
        count = 0
    else:
        int_err += err
        count += 1
    
    




